# Servidor
server.port=8080

# Base de datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:zonagisdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

# Consola H2 (útil para ver la BD en el navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Nombre de la aplicación
spring.application.name=zona-gis-api
